INSERT INTO `item_table` (`item_id`, `creater_id`, `item_date`, `item_coursetype`, `item_type`, `item_index`, `item_question`, `item_option`, `item_answer`, `item_picture`, `item_score`, `item_parse`) VALUES (11, 'admin', '2022-12-26 17:43', 'Java程序设计', '单选题', 1, 'java是什么', '编程语言###///', '///', '', 5, '真难');
INSERT INTO `item_table` (`item_id`, `creater_id`, `item_date`, `item_coursetype`, `item_type`, `item_index`, `item_question`, `item_option`, `item_answer`, `item_picture`, `item_score`, `item_parse`) VALUES (28, 'admin', '2022-12-22 17:20', 'Java程序设计', '问答题', 3, 'java三种特性', '', '封装 继承 多态', '', 10, '封装 继承 多态');
INSERT INTO `item_table` (`item_id`, `creater_id`, `item_date`, `item_coursetype`, `item_type`, `item_index`, `item_question`, `item_option`, `item_answer`, `item_picture`, `item_score`, `item_parse`) VALUES (29, 'admin', '2022-12-26 17:36', 'Java程序设计', '多选题', 1, '下列属于jsp中注释的有(）', '<%--  与 --%>###/###/** 与 **/###<!-- 与 -->', '<%--  与 --%>###<!-- 与 -->', '', 6, '');
INSERT INTO `item_table` (`item_id`, `creater_id`, `item_date`, `item_coursetype`, `item_type`, `item_index`, `item_question`, `item_option`, `item_answer`, `item_picture`, `item_score`, `item_parse`) VALUES (30, 'admin', '2022-12-26 17:36', 'Java程序设计', '问答题', 1, '多线程有几种实现方法,都是什么?同步有几种实现方法,都是什么?', '', '多线程有两种实现方法，分别是继承Thread类与实现Runnable接口同步的实现方面有两种，分别是synchronized,wait与notify', '', 10, '');
INSERT INTO `item_table` (`item_id`, `creater_id`, `item_date`, `item_coursetype`, `item_type`, `item_index`, `item_question`, `item_option`, `item_answer`, `item_picture`, `item_score`, `item_parse`) VALUES (31, 'admin', '2022-12-26 17:37', 'Java程序设计', '单选题', 1, '在Servlet处理请求的方式为: ', '以进程的方式###以程序的方式###以线程的方式###以响应的方式', '以线程的方式', '', 5, '');
INSERT INTO `item_table` (`item_id`, `creater_id`, `item_date`, `item_coursetype`, `item_type`, `item_index`, `item_question`, `item_option`, `item_answer`, `item_picture`, `item_score`, `item_parse`) VALUES (32, 'admin', '2022-12-26 17:38', 'Java程序设计', '多选题', 1, '有关会话跟踪技术描述正确的是()', 'Cookie是Web服务器发送给客户端的一小段信息，客户端请求时，可以读取该信息发送到服务器端###关闭浏览器意味着会话ID丢失，但所有与原会话关联的会话数据仍保留在服务器上，直至会话过期###在禁用Cookie时可以使用URL重写技术跟踪会话###隐藏表单域将字段添加到HTML表单并在客户端浏览器中显示', 'Cookie是Web服务器发送给客户端的一小段信息，客户端请求时，可以读取该信息发送到服务器端###关闭浏览器意味着会话ID丢失，但所有与原会话关联的会话数据仍保留在服务器上，直至会话过期###在禁用Cookie时可以使用URL重写技术跟踪会话', '', 6, '');
INSERT INTO `item_table` (`item_id`, `creater_id`, `item_date`, `item_coursetype`, `item_type`, `item_index`, `item_question`, `item_option`, `item_answer`, `item_picture`, `item_score`, `item_parse`) VALUES (33, 'admin', '2022-12-26 17:42', 'Java程序设计', '多选题', 1, '有关Servlet的生命周期说法正确的有（）', 'Servlet的生命周期由Servlet实例控制###init()方法在创建完Servlet实例后对其进行初始化，传递的参数为实现ServletContext接口的对象###service()方法响应客户端发出的请求###destroy()方法释放Servlet实例', 'init()方法在创建完Servlet实例后对其进行初始化，传递的参数为实现ServletContext接口的对象###service()方法响应客户端发出的请求###destroy()方法释放Servlet实例', '', 6, '');
INSERT INTO `item_table` (`item_id`, `creater_id`, `item_date`, `item_coursetype`, `item_type`, `item_index`, `item_question`, `item_option`, `item_answer`, `item_picture`, `item_score`, `item_parse`) VALUES (34, 'admin', '2022-12-26 17:42', 'Java程序设计', '单选题', 1, '在web.xml中使用()标签配置过滤器 ', '<filter>和<filter-mapping>###<filter-name>和<filter-class>###<filter>和<filter-class>###<filter-pattern>和<filter>', '<filter>和<filter-mapping>', '', 5, '');
INSERT INTO `admin_table` (`admin_id`, `admin_name`, `admin_password`) VALUES ('admin', 'admin', '21232f297a57a5a743894a0e4a801fc3');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 23, 'admin', '17,.00###15,.00###', '18,.00###', '20,2.51###', '19,6.28###', 8.8, '2019-08-02 07:29');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('student', 23, 'admin', '17,.00###15,.00###', '', '', '', 0, '2019-08-02 07:35');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 23, 'admin', '17,.00###15,.00###', '18,.00###', '20,3.22###', '19,8.04###', 11.26, '2021-03-15 21:42');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 23, 'admin', '17,.00###15,.00###', '18,.00###', '20,3.37###', '19,8.43###', 11.8, '2021-03-15 21:43');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 23, 'admin', '17,.00###15,.00###', '18,.00###', '20,1.91###', '19,4.78###', 6.69, '2022-12-22 16:43');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('', 0, '', '17,.00###15,.00###', '18,.00###', '20,1.97###', '19,4.94###', 6.91, '');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 23, 'admin', '17,.00###15,.00###', '18,.00###', '20,.23###', '19,.57###', 0.8, '2022-12-22 16:47');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 24, 'admin', '16,.00###14,.00###12,.00###', '23,.00###22,.00###21,.00###', '24,3.23###', '26,3.23###', 6.46, '2022-12-22 16:53');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 25, 'admin', '17,.00###15,1.00###', '18,.00###', '20,1.18###', '19,2.95###', 5.12, '2022-12-22 17:00');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 23, 'admin', '17,.00###15,.00###', '18,.00###', '20,3.18###', '19,7.95###', 11.13, '2022-12-22 17:03');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('', 0, '', '17,.00###15,.00###', '18,.00###', '20,4.00###', '19,9.99###', 13.98, '');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('', 0, '', '17,.00###15,.00###', '18,.00###', '20,.61###', '19,1.53###', 2.14, '');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('', 0, '', '17,.00###15,.00###', '18,.00###', '20,.96###', '19,2.41###', 3.37, '');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 23, 'admin', '17,.00###15,.00###', '18,.00###', '20,1.87###', '19,4.67###', 6.53, '2022-12-25 16:15');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('admin', 23, 'admin', '17,.00###15,.00###', '18,.00###', '20,.51###', '19,1.26###', 1.77, '2022-12-25 16:18');
INSERT INTO `check_table` (`student_id`, `paper_id`, `teacher_id`, `singlechoice_score`, `multichoice_score`, `fill_score`, `subjective_score`, `sum_score`, `check_date`) VALUES ('', 0, '', '17,.00###15,.00###', '18,.00###', '20,3.49###', '19,8.71###', 12.2, '');
INSERT INTO `course_table` (`course_id`, `course_name`, `course_type`, `course_begin`, `course_end`, `course_remark`, `course_status`) VALUES (1, 'Java', 'Java程序设计', '2019-08-01 00:00', '2019-08-31 00:00', '计算机必修课', '1');
INSERT INTO `course_table` (`course_id`, `course_name`, `course_type`, `course_begin`, `course_end`, `course_remark`, `course_status`) VALUES (6, 'Mysql', 'MySql', '2022-08-26 16:46', '2022-12-26 16:46', '掌握Mysql的基本操作与工作原理', '1');
INSERT INTO `exam_table` (`exam_id`, `paper_id`, `creater_id`, `exam_name`, `exam_type`, `pass_score`, `sum_score`, `create_date`, `exam_begin`, `exam_end`, `exam_last`, `exam_remark`) VALUES (10, 34, 'admin', '34234', '计算机', 5, 100, '2022-12-26 17:14', '2022-12-26 17:14', '2022-12-29 17:14', 60, '');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (48, 'admin', '2019-08-02 00:18', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (49, 'admin', '2019-08-02 00:48', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (50, 'admin', '2019-08-02 00:49', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (51, 'admin', '2019-08-02 00:55', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (52, 'admin', '2019-08-02 01:16', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (53, 'admin', '2019-08-02 07:27', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (54, 'admin', '2019-08-02 07:29', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (55, 'student', '2019-08-02 07:31', '登录', '学生', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (56, 'admin', '2019-08-02 08:23', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (57, 'admin', '2021-03-15 21:40', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (58, 'admin', '2022-12-21 21:08', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (59, 'admin', '2022-12-22 15:27', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (60, 'admin', '2022-12-22 15:36', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (61, 'admin', '2022-12-22 16:26', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (62, 'admin', '2022-12-22 16:27', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (63, 'admin', '2022-12-22 17:00', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (64, 'admin', '2022-12-22 17:19', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (65, 'admin', '2022-12-22 17:19', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (66, 'admin', '2022-12-22 17:20', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (67, 'admin', '2022-12-22 17:21', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (68, 'admin', '2022-12-25 16:10', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (69, 'admin', '2022-12-25 16:11', '登出', '登出', '/login/logout');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (70, 'admin', '2022-12-25 16:12', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (71, 'admin', '2022-12-25 20:20', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (72, 'admin', '2022-12-26 12:08', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (73, 'admin', '2022-12-26 12:08', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (74, 'admin', '2022-12-26 12:08', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (75, 'admin', '2022-12-26 12:09', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (76, 'admin', '2022-12-26 12:10', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (77, 'admin', '2022-12-26 12:10', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (78, 'admin', '2022-12-26 12:10', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (79, 'admin', '2022-12-26 12:20', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (80, 'admin', '2022-12-26 12:58', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (81, 'admin', '2022-12-26 12:58', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (82, 'admin', '2022-12-26 12:59', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (83, 'admin', '2022-12-26 13:00', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (84, 'admin', '2022-12-26 13:00', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (85, 'admin', '2022-12-26 13:00', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (86, 'admin', '2022-12-26 13:01', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (87, 'admin', '2022-12-26 13:01', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (88, 'admin', '2022-12-26 13:02', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (89, 'admin', '2022-12-26 13:02', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (90, 'admin', '2022-12-26 15:55', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (91, 'admin', '2022-12-26 15:55', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (92, 'admin', '2022-12-26 15:55', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (93, 'admin', '2022-12-26 15:55', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (94, 'admin', '2022-12-26 15:55', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (95, 'admin', '2022-12-26 15:56', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (96, 'admin', '2022-12-26 15:56', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (97, 'admin', '2022-12-26 15:56', '登出', '登出', '/login/logout');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (98, 'admin', '2022-12-26 15:56', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (99, 'admin', '2022-12-26 15:56', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (100, 'admin', '2022-12-26 15:57', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (101, 'admin', '2022-12-26 15:58', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (102, 'admin', '2022-12-26 15:58', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (103, 'admin', '2022-12-26 15:59', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (104, 'admin', '2022-12-26 15:59', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (105, 'admin', '2022-12-26 15:59', '登出', '登出', '/login/logout');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (106, 'admin', '2022-12-26 16:00', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (107, 'admin', '2022-12-26 16:05', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (108, 'admin', '2022-12-26 16:07', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (109, 'admin', '2022-12-26 16:08', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (110, 'admin', '2022-12-26 16:08', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (111, 'admin', '2022-12-26 16:09', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (112, 'admin', '2022-12-26 16:09', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (113, 'admin', '2022-12-26 16:15', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (114, 'admin', '2022-12-26 16:18', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (115, 'admin', '2022-12-26 16:21', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (116, 'admin', '2022-12-26 16:21', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (117, 'admin', '2022-12-26 16:22', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (118, 'admin', '2022-12-26 16:23', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (119, 'admin', '2022-12-26 16:24', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (120, 'admin', '2022-12-26 16:26', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (121, 'admin', '2022-12-26 16:30', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (122, 'admin', '2022-12-26 16:34', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (123, 'admin', '2022-12-26 16:36', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (124, 'admin', '2022-12-26 16:36', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (125, 'admin', '2022-12-26 16:39', '登出', '登出', '/login/logout');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (126, 'admin', '2022-12-26 16:39', '登录', '管理员', '/login');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (127, 'admin', '2022-12-26 17:08', '登出', '登出', '/login/logout');
INSERT INTO `log_table` (`log_id`, `op_id`, `op_date`, `op_type`, `op_msg`, `op_page`) VALUES (128, 'admin', '2022-12-26 17:08', '登录', '管理员', '/login');
INSERT INTO `paper_table` (`paper_id`, `paper_name`, `creater_id`, `create_date`, `paper_type`, `paper_index`, `singlechoice_question`, `multichoice_question`, `fill_question`, `subjective_question`, `paper_score`, `paper_secrecy`, `paper_remark`) VALUES (34, 'Java第一次测试', 'admin', '2022-12-26 17:14', '计算机', 3, '11???100???单选题???1', '', '', '', 100, '保密', '1672046078451');
INSERT INTO `student_table` (`student_id`, `student_name`, `student_password`, `student_academy`, `student_major`, `student_school`) VALUES ('student', 'student', '202cb962ac59075b964b07152d234b70', '计算机学院', '软件工程', '成都信息工程大学');
INSERT INTO `teacher_table` (`teacher_id`, `teacher_name`, `teacher_password`, `teacher_academy`, `teacher_major`, `teacher_school`) VALUES ('teacher', 'teacher', '202cb962ac59075b964b07152d234b70', '软件工程学院', '软件工程', '成都信息工程大学');
